[package]
name = "room"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixels = "0.12.0"
winit = "0.27"
winit_input_helper = "0.13"
line_drawing = "1"